### ISSUE TITLE
长度字段刚好为 0x80 的时候 获取长度有bug?

### ISSUE THREAD

**Issue by Lorem3** [ZhenlyChen/X.509Reader#1]
从您写的文档中说
>> 还有一种特殊情况，这个字节为0x80，表示数据块长度不定，由数据块结束标识结束数据块。

但是代码 似乎没处理这种情况,是不是 证书不会有这种情况出现?
```
/ 长度、长度占用
lenData getLen(byte* data, int i) {
  lenData res;
  res.lenLen = 1;
  if (data[i] & 0x80) {
    int len_len = data[i] & 0x7f;
    int len = 0;
    i++;
    for (int j = 0; j < len_len; j++) {
      len <<= 8;
      len += data[i + j];
    }
    res.len = len;
    res.lenLen += len_len;
  } else {
    res.len = data[i] & 0x7f;
  }
  return res;
}

```

**Comment by ZhenlyChen** [comment]
@vitock 看了一下，这里当时的确是忘记处理了，当时在处理主流的证书时，还没遇到这种情况。按照ANS.1的标准来说，这种写法又确实是被允许的，只是一般用于未知长度的消息传输中，用于证书中可能较少。

**Comment by Lorem3** [comment]
> 看了一下，这里当时的确是忘记处理了，当时在处理主流的证书时，还没遇到这种情况。按照ANS.1的标准来说，这种写法又确实是被允许的，只是一般用于未知长度的消息传输中，用于证书中可能较少。

刚刚查了下,确实DER格式  是要定长的标志 [wiki](https://en.wikipedia.org/wiki/X.690#DER_encoding)
 
全网找解析证书的方法,就您这个最简洁,谢谢 :)

一个小小的建议,您目前是把解析结果平铺到一个数组里面,能解析成和证书一样的树形结构就更完美了
因为找commonName的时候,发现 颁发者和证书本身名字都是  2.5.4.3 ,这样遍历查找的话给人一种不踏实的感觉
```
[
 [ ]
 [ [] , []]
...
]
```
